<?php

namespace Vortice;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../src/Vortice/Vortice.php';

/**
 * Test class for Vortice.
 * Generated by PHPUnit on 2010-09-25 at 05:32:18.
 */
class VorticeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Vortice
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Vortice;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
